### ISSUE TITLE
Move svg to another repo

### ISSUE THREAD

**Issue by CzBiX** [Templarian/MaterialDesign-Webfont#49]
Does it possible to move svg font files to another undependent repo? It's rarely used(Only for iOS <= 4.x ?), but take 2x space than all other fonts.

```
svg size: 3.88M
eot + woff  + woff2 + ttf size: 1.43M
```

Releated info:

> There's technically another container format, the SVG font container, but IE and Firefox never supported it, and it is now deprecated in Chrome.

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization

> SVG Font (deprecated)

https://www.w3.org/TR/css-fonts/#font-face-src-format-types

**Comment by industral** [comment]
Agree. Also faced the same issue. bundle got extremely large.
Need an option to build css from scss based on passed required font types, or just leave css without @font-face. User can write it's own desired @font-face and include any fonts, thanks to webpack and other build system - it's very easy bundling.

**Comment by industral** [comment]
Possible workaround for now is

```scss
@import "~@mdi/font/scss/variables";
@import "~@mdi/font/scss/functions";
@import "~@mdi/font/scss/core";
@import "~@mdi/font/scss/icons";
@import "~@mdi/font/scss/extras";
@import "~@mdi/font/scss/animated";

@font-face {
  font-family: "Material Design Icons";
  src: url("~@mdi/font/fonts/materialdesignicons-webfont.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
}
```

In that case webpack will bundle (or copy) only `woff2` file. It's also important for those who use PWA pre-caching, where list of cached assets generated. In that case only one item will be included and cached.
