### ISSUE TITLE
[Q] - It is possible to alter generating of css files ?

### ISSUE THREAD

**Issue by MilosMosovsky** [Templarian/MaterialDesign-Webfont#6]
Hello @Templarian , thank you for your update, also i just started using mdi inside my css with my mixins. (for example i am adding magnify icon to input box via :after pseudo selector). My problem is that i created this class 

```css
&:after {
  content     : "\f3ab";
  @extend .mdi-icon;
}
```

But problems is , that when you upgraded to new version your HEX-codes was changed, so every icon in my application stopped working :) . It is possible to generate inside your _icons.scss file variable for each icon so it would be like

```css
$mdi-account : "\f101";
```

after this i can include your _icons.css file and only call and my build will not be broken after each upgrade? Also same approach has Font-Awesome icon set inside sass files. When i look to your _icons.scss it looks like generated file, so i think it would not be big deal add another loop to generate named variables for hexes. Thanks.
```css
&:after {
  content     :  $mdi-account;
  @extend .mdi-icon;
}
```
